sudo: false
language: ruby
rvm:
  - 2.4.1
env:
  - TARGET_DIR=mobile-ui-testing-android
install:
  - cd $TRAVIS_BUILD_DIR/$TARGET_DIR && bundle install
before_script:
  - cd $TRAVIS_BUILD_DIR/$TARGET_DIR && bundle exec fastlane android review

