sudo: false
language: ruby
rvm:
  - 2.4.1
env:
  - TARGET_DANGERFILE="mobile-ui-testing-android/Dangerfile"
  - TARGET_DANGERFILE="mobile-ui-testing-ios/Dangerfile"
cache:
  - bundler
before_script:
  - bundle exec danger --dangerfile=$TARGET_DANGERFILE
script: skip

